const seed={patients:[{id:"P001",name:"Rahul Sharma",age:35,gender:"Male",phone:"9876543210",disease:"Fever",doctor:"Dr. Amit",admission:"2026-09-09",address:"Udaipur"}],doctors:[{id:"D001",name:"Dr. Amit",specialization:"Cardiologist",phone:"9876500001",experience:10,department:"Cardiology"},{id:"D002",name:"Dr. Neha",specialization:"Neurologist",phone:"9876500002",experience:8,department:"Neurology"}],appointments:[{id:"A001",patient:"Rahul Sharma",doctor:"Dr. Amit",department:"Cardiology",date:"2026-09-10",time:"10:30",status:"Confirmed"}],bills:[]};
function get(k){let x=localStorage.getItem(k);if(x===null){localStorage.setItem(k,JSON.stringify(seed[k]||[]));return seed[k]||[]}return JSON.parse(x)}
function set(k,v){localStorage.setItem(k,JSON.stringify(v))}
function id(prefix){return prefix+Date.now().toString().slice(-5)}
function nav(){return `<aside class="sidebar" id="side"><div class="brand">🏥 MediCare</div><ul>
<li><a href="index.html">📊 Dashboard</a></li><li><a href="patients.html">👥 Patients</a></li><li><a href="doctors.html">🩺 Doctors</a></li><li><a href="appointments.html">📅 Appointments</a></li><li><a href="billing.html">💳 Billing</a></li></ul><button class="logout" onclick="logout()">↪ Logout</button></aside>`}
document.addEventListener("DOMContentLoaded",()=>{let s=document.getElementById("sidebar");if(s)s.innerHTML=nav();document.querySelectorAll(".sidebar a").forEach(a=>{if(a.pathname===location.pathname)a.classList.add("active")})})
function toggleSidebar(){document.getElementById("side")?.classList.toggle("open")}
function logout(){localStorage.removeItem("loggedIn");location.href="login.html"}
function renderDashboard(){dashPatients.textContent=get("patients").length;dashDoctors.textContent=get("doctors").length;dashAppointments.textContent=get("appointments").length;dashBills.textContent=get("bills").length;let a=get("appointments").slice(-5).reverse();recentAppointments.innerHTML=a.length?a.map(x=>`<tr><td>${x.patient}</td><td>${x.doctor}</td><td>${x.date}</td><td>${x.time}</td><td><span class="status ${x.status.toLowerCase()}">${x.status}</span></td></tr>`).join(""):`<tr><td colspan="5">No appointments found</td></tr>`}
function setupPatientPage(){renderPatients();patientForm.addEventListener("submit",e=>{e.preventDefault();let f=new FormData(e.target),a=get("patients");a.push({id:id("P"),name:f.get("name"),age:f.get("age"),gender:f.get("gender"),phone:f.get("phone"),disease:f.get("disease"),doctor:f.get("doctor"),admission:f.get("admission"),address:f.get("address")});set("patients",a);e.target.reset();renderPatients();alert("Patient added successfully!")})}
function renderPatients(){let q=(patientSearch?.value||"").toLowerCase();let a=get("patients").filter(x=>(x.name+x.phone+x.disease).toLowerCase().includes(q));patientTable.innerHTML=a.length?a.map(x=>`<tr><td>${x.id}</td><td>${x.name}</td><td>${x.age}</td><td>${x.gender}</td><td>${x.phone}</td><td>${x.disease}</td><td>${x.doctor}</td><td><button class="btn danger" onclick="deleteItem('patients','${x.id}',renderPatients)">Delete</button></td></tr>`).join(""):`<tr><td colspan="8">No patients found</td></tr>`}
function setupDoctorPage(){renderDoctors();doctorForm.addEventListener("submit",e=>{e.preventDefault();let f=new FormData(e.target),a=get("doctors");a.push({id:id("D"),name:f.get("name"),specialization:f.get("specialization"),phone:f.get("phone"),experience:f.get("experience"),department:f.get("department")});set("doctors",a);e.target.reset();renderDoctors();alert("Doctor added successfully!")})}
function renderDoctors(){let q=(doctorSearch?.value||"").toLowerCase();let a=get("doctors").filter(x=>(x.name+x.specialization+x.department).toLowerCase().includes(q));doctorTable.innerHTML=a.length?a.map(x=>`<tr><td>${x.id}</td><td>${x.name}</td><td>${x.specialization}</td><td>${x.department}</td><td>${x.experience} years</td><td>${x.phone}</td><td><button class="btn danger" onclick="deleteItem('doctors','${x.id}',renderDoctors)">Delete</button></td></tr>`).join(""):`<tr><td colspan="7">No doctors found</td></tr>`}
function setupAppointmentPage(){renderAppointments();appointmentForm.addEventListener("submit",e=>{e.preventDefault();let f=new FormData(e.target),a=get("appointments");a.push({id:id("A"),patient:f.get("patient"),doctor:f.get("doctor"),department:f.get("department"),date:f.get("date"),time:f.get("time"),status:f.get("status")});set("appointments",a);e.target.reset();renderAppointments();alert("Appointment booked successfully!")})}
function renderAppointments(){let q=(appointmentSearch?.value||"").toLowerCase();let a=get("appointments").filter(x=>(x.patient+x.doctor+x.department).toLowerCase().includes(q));appointmentTable.innerHTML=a.length?a.map(x=>`<tr><td>${x.id}</td><td>${x.patient}</td><td>${x.doctor}</td><td>${x.department}</td><td>${x.date}</td><td>${x.time}</td><td><span class="status ${x.status.toLowerCase()}">${x.status}</span></td><td><button class="btn danger" onclick="deleteItem('appointments','${x.id}',renderAppointments)">Delete</button></td></tr>`).join(""):`<tr><td colspan="8">No appointments found</td></tr>`}
function setupBillingPage(){renderBills();billForm.addEventListener("submit",e=>{e.preventDefault();let f=new FormData(e.target),total=+f.get("consultation")+ +f.get("medicine")+ +f.get("room"),a=get("bills");a.push({id:id("B"),patient:f.get("patient"),doctor:f.get("doctor"),total,payment:f.get("payment"),date:new Date().toISOString().slice(0,10)});set("bills",a);e.target.reset();renderBills();alert("Bill generated successfully!")})}
function renderBills(){let q=(billSearch?.value||"").toLowerCase();let a=get("bills").filter(x=>(x.patient+x.doctor).toLowerCase().includes(q));billTable.innerHTML=a.length?a.map(x=>`<tr><td>${x.id}</td><td>${x.patient}</td><td>${x.doctor}</td><td>₹${x.total.toFixed(2)}</td><td>${x.payment}</td><td>${x.date}</td><td><button class="btn danger" onclick="deleteItem('bills','${x.id}',renderBills)">Delete</button></td></tr>`).join(""):`<tr><td colspan="7">No bills found</td></tr>`}
function deleteItem(k,i,fn){if(confirm("Are you sure you want to delete this record?")){set(k,get(k).filter(x=>x.id!==i));fn();}}
